### ISSUE TITLE
some issues from compiling process

### ISSUE THREAD

**Issue by TonyCMU** [coincar-sim/lanelet_rviz_plugin_ros#1]
Thanks for the excellent works. I am now trying to use it with Lanelet2.
After downloaded the package to the src dir of ROS/Melodic, I used the catkin build or cmake to compile it, but I failed, it said,
/.../catkin_ws/src/lanelet_rviz_plugin_ros/src/map_element.cpp:31:0:
/.../catkin_ws/src/lanelet_rviz_plugin_ros/src/map_element.hpp:47:10: fatal error: ros/ros.h: No such file or directory
 #include <ros/ros.h>
          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/lanelet_rviz_plugin_ros.dir/src/map_element.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /.../catkin_ws/src/lanelet_rviz_plugin_ros/src/lanelet_plugin.cpp:31:0:
/.../catkin_ws/src/lanelet_rviz_plugin_ros/src/lanelet_plugin.hpp:38:10: fatal error: ros/ros.h: No such file or directory
 #include <ros/ros.h>

Did I miss something? I think I have installed the dependent libs already.
Any helps are welcome.

**Comment by m-naumann** [comment]
Hi and sorry for the late reply.
Sounds strange to me, that ros is not found. Would you please try the full coincar-sim setup ([only a few lines as explained here](https://github.com/coincar-sim/coincarsim_getting_started#installation)) and tell me whether you encounter the same problem?
