### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by xiaozhi12345678** [coincar-sim/lanelet_rviz_plugin_ros#2]
Hello,I have an issue with it,and I am looking forward  for your reply.I catkin_make succeeded,but when I input command "roslaunch lanelet_rviz_plugin_ros sample_lanelet_viz.launch",the error occurs,"PluginlibFactory: The plugin for class 'lanelet_rviz_plugin_ros::LaneletMapPlugin' failed to load.  Error: Failed to load library /.../catkin_ws/devel/lib//liblanelet_rviz_plugin_ros.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /.../catkin_ws/devel/lib//liblanelet_rviz_plugin_ros.so: undefined symbol: _ZTVN22lanelet2_interface_ros20Lanelet2InterfaceRosE)".Could you please tell me how to solve it, thank you!

**Comment by m-naumann** [comment]
Hi, I recommend the use of `catkin build` over the deprecated `catkin_make`, would you please try that, and if you encounter the same problem, try the full coincar-sim setup ([only a few lines as explained here](https://github.com/coincar-sim/coincarsim_getting_started#installation)) to figure out potential problems with your ros setup?

**Comment by Shelfcol** [comment]
@xiaozhi12345678  Can you tell me how you catkin_make succeed? Could you please tell me the detailed proceduer?Thank you

**Comment by m-naumann** [comment]
In the [travis build](https://travis-ci.org/coincar-sim/coincarsim_getting_started) you can see line by line how `catkin build` works. The old `catkin_make` is deprecated, see [catkin documentation](https://catkin-tools.readthedocs.io/en/latest/index.html).

**Comment by xiaozhi12345678** [comment]
@Shelfcol when I catkin_make ,the error is about QT and eigen, it says couldn't find .h file or other file and I add some sentences such as"include_directories("/.../QT/qtcore")" to CMakeLists.txt to fix the errors.The author recommended source is very useful and don't come up the errors, so I also advice you use the coincar-sim setup to replace this.

**Comment by xiaozhi12345678** [comment]
@m-naumann Hi, After I download the coincar-sim setup, catkin build succeeded.There are two issues I want to ask you.The first is I use my map(.osm) in launch file but rviz doesn't come up regulatory elements even if I enable the option for it.The second is how to combine route planning and rviz,for example ,I want to input start point and destination and I hope the car can run a route in rviz. I see in launch file you use trj.osm to guide the car,but I want it auto,how can I do it? Thank you!

**Comment by m-naumann** [comment]
Good that `catkin build` works.

The only thing you see about the regulatory element is it's reference line, currently. It is displayed in red. Feel free to fork the plugin and use your map in the sample launchfile, such that I can have a look.

For the second question: The linestring `traj1.osm` is only used for the initialization of the vehicle, afterwards they plan a trajectory along a random route using the lanelet2 map. If you want a specific route, you have to implement it yourself [here](https://github.com/coincar-sim/sim_sample_planning_ros_tool/blob/release/src/planner/util_planner.hpp#L192-L201). 

If you have further questions about either of those topics, please open a new issue in the respective repository.
