### ISSUE TITLE
sample_lanelet_viz error

### ISSUE THREAD

**Issue by joachim-p** [coincar-sim/lanelet_rviz_plugin_ros#3]
Hi,
I can't get sample_lanelet_viz.launch to load due to parsing errors of the provided example map. The exact error message is:
>Error during map loading with lanelet2_interface_ros: Errors ocurred while parsing Lanelet Map: - Error parsing primitive 45034: Failed to generate boundary (self-intersecting?) - Error parsing primitive 45034: Areas must have exactly one outer ring! - Error parsing primitive 45042: Failed to generate boundary (self-intersecting?) - Error parsing primitive 45042: Areas must have exactly one outer ring! [...]

Is the provided map outdated ?

**Comment by m-naumann** [comment]
Hi,

sounds like the xml parser doesn't understand the map. Do you have `,` as decimal separator? It should be `.`.
You can check your settings with 

```
$ locale
```
it should be 
```
LC_NUMERIC="en_US.UTF-8"
```

Please let me know whether changing your locale settings fixes the problem.

**Comment by joachim-p** [comment]
Sorry for the late reply,
changing my locale settings fixed the problem. I can now see 3 intersections.
Thanks a lot.
