### ISSUE TITLE
display some points in lanelet map

### ISSUE THREAD

**Issue by xiaozhi12345678** [coincar-sim/lanelet_rviz_plugin_ros#8]
Hi,I want to display some points which are on the centerline in my lanelet map,I use “BasicPoint3d point=p1.forward(centerline_point);”,I send point to rviz use geometry_msgs::Point,but the point in rviz is not on the lanelet centerline,it is far away from the map.Is there something wrong?

**Comment by m-naumann** [comment]
The lanelet map internally stores all the data in Cartesian coordinates using the `Projection` that you determined while loading the map. 

Can you share all relevant parts of the code? What is `centerline_point` and `p1`? Actually the whole centerline should consist of [ConstPoint3d](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/1d316d1224453b300f657fe6ae626c2927b3a5e7/lanelet2_core/include/lanelet2_core/primitives/Point.h#L201), so you can transform that into `geometry_msgs::Point` straight away.
