### ISSUE TITLE
Map is not displayed on some machines

### ISSUE THREAD

**Issue by autonomobil** [coincar-sim/lanelet_rviz_plugin_ros#9]
Hey, I use the plugin to visualize a lanelet map in rviz and it works well on my machine. All the lines of the lanelets are displayed. 

However if I try it on another machine (same code, same OS, same ROS version, etc.) nothing is displayed in rviz. There is no error or warning message, everything seems ok. I checked in _lanelet_plugin.cpp_ if the map pointer and origin frame id are received and that is the case. Can somebody give me a hint where to look to solve this problem?

![image](https://user-images.githubusercontent.com/31781343/76170664-58b42600-6184-11ea-89e2-31b2cbca1425.png)

**Comment by m-naumann** [comment]
Hi Moritz, my guess is that the decimal "point" is the problem: At least in rviz, it is `,` but should be `.`. You should see [this error(edit: warning)](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/f0512231aca66aa44d08d904de34c2008d8e75b1/lanelet2_io/src/OsmHandlerWrite.cpp#L286) in your console. 

Could you try to set it to `.` as in [the full simulation framework setup](https://github.com/coincar-sim/simulation_initialization_ros_tool/blob/release/launch/_whole_framework.launch#L56) (Or simply install/launch the full framework on the machine with problems, as [described here](https://github.com/coincar-sim/coincarsim_getting_started#installation))?

**Comment by autonomobil** [comment]
You are right! 

With 
_(in terminal were rviz is started)_
```
export LC_NUMERIC="en_US.UTF-8"
``` 
or 

_(in launch file which starts rviz)_
```
    <!-- Define point instead of comma as decimal seperator -->
    <env name="LC_NUMERIC" value="en_US.UTF-8"/>
```
it works.

The only thing: There was no warning whatsoever. Would it make sense to change[ `std::cerr`](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/f0512231aca66aa44d08d904de34c2008d8e75b1/lanelet2_io/src/OsmHandlerWrite.cpp#L289) to `ROS_ERROR_STREAM` ?

**Comment by m-naumann** [comment]
Perfect.

Thanks for the hint, displaying the warning in rviz would be the best I guess, we'll look into that. (`ROS_ERROR_STREAM` is not possible because lanelet2 is ROS-independent)

**Comment by Wing-ka-king** [comment]
Hi!
On my machine, I cannot visualize any lanelet from the map on rviz even after setting the `export LC_NUMERIC="en_US.UTF-8"`.
I see no error while launching the sample_lanelet_viz.launch file.
![Screenshot from 2020-12-30 11-47-33](https://user-images.githubusercontent.com/9566327/103333731-ddb25800-4a94-11eb-8d85-d9ae635333df.png)

**Comment by m-naumann** [comment]
Could you please pull again and try again? Actually, the sample launchfile was missing the lat lon arguments (default values were removed in `lanelet2_interface_ros`) so I wonder why it did start at all on your machine. If you just set lat and lon to 0 each, the map is displayed but somewhere far away from the origin of the map frame

**Comment by Wing-ka-king** [comment]
Yeah, it works now.
Also, for my custom osm maps, besides changing the lat and lon, I also had to change x-y focal points in rviz settings file to locate the map.

**Comment by m-naumann** [comment]
It is implemented such that 0,0 of the map frame is exactly in the lat lon coordinates you specify. So if you set the origin correctly, there should be no need do change xy
